export const email = 'biuro@virtoffice.pl'

export const utcOffset = 2

export const packageMonthCoeff = 1
export const packageKwartalCoeff = 2.5
export const packageYearCoeff = 9

export const week = {
    pl: ['pon', 'wto', 'śro', 'czw', 'pią', 'sob', 'nie'],
    ua: ['пнд', 'втр', 'срд', 'чтв', 'птн', 'сбт', 'ндл'],
    en: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']
}

export const monthNames = {
    pl: [
        "Styczeń",
        "Luty",
        "Marzec",
        "Kwiecień",
        "Maj",
        "Czerwiec",
        "Lipiec",
        "Sierpień",
        "Wrzesień",
        "Październik",
        "Listopad",
        "Grudzień"
    ],
    ua: [
        "Січень",
        "Лютий",
        "Березень",
        "Квітень",
        "Травень",
        "Червень",
        "Липень",
        "Серпень",
        "Вересень",
        "Жовтень",
        "Листопад",
        "Грудень"
    ],
    en: [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December"
    ],
}

export const pathnames = {
    pl: {
        home: 'wynajem adresu dla firm',
        cennik: 'cennik i usługi',
        ksiegowosc: 'księgowość',
        polityka : 'polityka prywatności',
        regulamin : 'regulamin'
    },
    ua: {
        home: 'оренда адресу для компаній',
        cennik: 'ціни та послуги',
        ksiegowosc: 'бухгалтерия',
        polityka : 'polityka prywatności',
        regulamin : 'regulamin'
    },
    en: {
        home: 'lease of address for companies',
        cennik: 'prices and services',
        ksiegowosc: 'accounting',
        polityka : 'privacy policy',
        regulamin : 'terms and conditions'
    }
}

export const buttonNames = {
    pl: {
        wynajecie: 'Wynajmij adres',
        login: 'Zaloguj się',
        profil: "profil",
        cancel: 'anuluj',
        reserve: "zarezerwuj",
        prices: "cennik",
	    accounting: "księgowość",
	    conditions: "regulamin",
	    policy: "polityka prywatności",
	    login2: "zaloguj",
        register: "zarejestruj",
        logout: "wyloguj",
        next: "Dalej",
        pay: "Zaplać",
        loginAndPay: 'Zaloguj się i zaplać',
        cennik: 'cennik',
        ksiegowosc: 'ksiegowosc',
        regulamin: 'regulamin',
        polityka : 'polityka prywatności',
        myProfile: '1. Mój profil',
        pakiet: '2. Pakiet',
        pack: 'Pakiet',
        rozliczenia: '3. Rozliczenia',
        rezerwacja: '4. Rezerwacja sali konferencyjnej',
        myReservations: "— Moje Rezerwacje",
        menuProfile: '1. profil',
        menuPakiet: '2. mój pakiet',
        menuRozliczenia: '3. rozliczenia',
        menuRezerwacja: '4. rezerwacja sali konferencyjnej',
        menuMyReservations: "— moje rezerwacje",
        save: 'ZAPISZ',
        edit: 'edytuj',
        forget: "Nie pamiętam hasła",
        back: "powrót",
        register2: "zarejestruj się",

    },
    ua :{
        wynajecie: 'ЗНЯТИ АДРЕСУ',
        login: 'Увійти',
        profil: "профіль",
        cancel: 'скасувати',
        reserve: "зарезервувати",
        prices: "прайс лист",
	    accounting: "бухгалтерія",
	    conditions: "нормативні акти",
        policy: "політика конфіденційності",
        login2: 'увійдіть',
        register: "зареєструватись",
        logout: "logout",
        next: "Далі",
        pay: "ОПЛАТИТИ",
        loginAndPay: 'Увійти та ОПЛАТИТИ',
        cennik: 'Прайс лист',
        ksiegowosc: 'бухгалтерія',
        regulamin: "нормативні акти",
        polityka: "політика конфіденційності",
        myProfile: '1. Мій профіль',
        pakiet: '2. Пакет',
        pack: 'Пакет',
        rozliczenia: '3. Розрахунки',
        rezerwacja: '4. Бронювання офісу',
        myReservations: "- Мої резервації",
        menuProfile: '1. профіль',
        menuPakiet: '2. пакет',
        menuRozliczenia: '3. розрахунки',
        menuRezerwacja: '4. бронювання офісу',
        menuMyReservations: "— мої резервації",
        save: 'ZAPISZ',
        edit: 'РЕДАГУВАТИ',
        forget: "Nie pamiętam hasła",
        back: "Повернутися",
        register2: "zarejestruj się",

    },
    en: {
        wynajecie: 'LEASE ADDRESS',
        login: 'log in',
        profil: "profil",
        cancel: 'cancel',
        reserve: "book",
        prices: "prices",
	    accounting: "accounting",
	    conditions: "terms and conditions",
        policy: "privacy policy",
        login2: 'log in',
        register: "register",
        logout: "log out",
        next: "next",
        pay: "Pay",
        loginAndPay: 'log in and pay',
        cennik: 'prices',
        ksiegowosc: 'accounting',
        regulamin: 'terms and conditions',
        polityka : 'privacy policy',
        myProfile: '1. Mój profil',
        pakiet: '2. Pakiet',
        pack: 'Pakiet',
        rozliczenia: '3. Rozliczenia',
        rezerwacja: '4. Rezerwacja biura',
        myReservations: "— Moje Rezerwacje",
        menuProfile: '1. profil',
        menuPakiet: '2. mój pakiet',
        menuRozliczenia: '3. rozliczenia',
        menuRezerwacja: '4. rezerwacja biura',
        menuMyReservations: "— moje rezerwacje",
        save: 'save',
        edit: 'edit',
        forget: "I don’t remember password",
        back: "powrót",
        register2: "register",

    }
}

export const phrases = {
    pl: {
        footerOne: "Działaj z dowolnego miejsca na świecie dzięki opcji biura wirtualnego.",
        footerTwo: "Skontaktuj sie z nami:",
        cennikTitleOne: 'Wirtualny adres',
        cennikTitleTwo: 'Optymalny pakiet',
        cennikTitleThree: 'Profesjonalne biuro',
        plnPerMonth: 'PLN/miesiąc',
        selectPackage: '1. wybór usługi biura wirtualnego:',
        selectPeriod: '2. wybierz profesjonalny adres swojej firmy:',
        month: 'Miesiąc',
        kwartal: 'Kwartał',
        year: 'Rok',
        sum: 'Podsumowanie:',
        price: 'Cena:',
        myProfile: 'Mój profil',
        pakiet: 'Pakiet',
        pakietDescription: 'Wpisz nazwę lub kod pocztowy miasta, w którym chcesz wybrać adres firmy. Dostępne adresy i miesięczny koszt wyświetlą się poniżej.',
        updated: 'zaktualizowany',
        ended: 'kończy się',
        changePackage: 'zmień pakiet',
        packDescription1: 'Profesjonalny adres z obsługą poczty i odbieraniem połączeń telefonicznych oraz dostęp bez rezerwacji do naszej globalnej sieci salonów biznesowych',
        packDescription2: 'Profesjonalny adres z obsługą poczty i odbieraniem połączeń telefonicznych oraz dostęp bez rezerwacji do naszej globalnej sieci salonów biznesowych',
        packDescription3: 'Profesjonalny adres z obsługą poczty i odbieraniem połączeń telefonicznych oraz dostęp bez rezerwacji do naszej globalnej sieci salonów biznesowych',
        packDescription4: 'Profesjonalny adres z obsługą poczty i odbieraniem połączeń telefonicznych oraz dostęp bez rezerwacji do naszej globalnej sieci salonów biznesowych',
        rozliczenia: 'Rozliczenia',
        rezerwacja: 'Rezerwacja biura',
        myReservations: "Moje Rezerwacje",
        login: 'Login',
        nameSurname: 'Imię i Nazwisko',
        adress: 'Adres',
        phone: 'Telefon',
        firmName: 'Nazwa Firmy',
        nip: 'NIP',
        nipPlaceholder: 'NIP',
        changePassword: 'Zmień hasło:',
        newPassword: 'Nowe Hasło',
        repeatPassword: 'Powtórz nowe hasło',
        passwordMessage1: "Hasło musi mieć co najmniej sześć znaków.",
        passwordMessage2: 'Hasło zostało pomyślnie zmienione!',
        passwordMessage3: "Powtórzone hasło nie jest zgodne z hasłem.",
        requiredField: 'Pole wymagane',
        profileMessage1: 'Nie wygląda jak prawdziwy e-mail.',
        profileMessage2: 'Nie wygląda jak prawdziwy numer telefonu.',
        profileMessage3: 'Nie wygląda jak numer NIP.',
        all: 'Wszystkie',
        currentMonth: 'Obecny miesiąc',
        number: 'Nr',
        nazwa: 'Nazwa',
        date: 'Data',
        wartosc: 'Wartość',
        receipt: 'Paragon',
        yourReservations: 'Twoje rezerwacje',
        code: 'kod dostępu:',
        yourDisplay: 'Twój ekran',
        displayText: 'Lub wprowadź żądany tekst.',
        yourPhrase: "Twoja fraza",
        menuContentText1: 'Działaj z dowolnego miejsca na świecie dzięki opcji biura wirtualnego.',
        menuContentText2: 'Skontaktuj sie z nami:',
        authMessage1: 'Błąd zakupu pakietu.',
        authMessage2: 'Masz niedokończony pakiet.',
        authMessage3: 'there is no user or password wrong',
        authMessage4: 'This is an error message',
        authMessage5: 'Nie wygląda jak prawdziwy email adress...',
        authMessage6: 'Link do zresetowania hasła został wysłany na e-mail',
        authMessage7: 'This username is already in use by another account.',
        authMessage8: 'Password should be at least 6 digits',
        authMessage9: 'Passwords are not the same...',
        authMessage10: 'Nie wygląda jak prawdziwy numer telefonu.',
        authMessage11: 'The email address is already in use by another account.',
        authMessage12: 'E-mail podany podczas rejestracji',
        password: 'Hasło',
        email: 'E-mail',
        step: 'step'
    },
    ua: {
        footerOne: "Дійте з будь-якої точки світу завдяки можливості віртуального офісу.",
        footerTwo: "Зв'яжіться з нами:",
        cennikTitleOne: 'Віртуальна адреса',
        cennikTitleTwo: 'Пакет Оптимальний',
        cennikTitleThree: 'Професійний кабінет',
        plnPerMonth: 'Злотих / місяць',
        selectPackage: '1. вибір послуги віртуального офісу:',
        selectPeriod: '2. виберіть професійну адресу вашої компанії:',
        month: 'Місяць',
        kwartal: 'Квартал',
        year: 'Рік',
        sum: 'Короткий Зміст послуги:',
        price: 'Ціна:',
        myProfile: 'Мій профіль',
        pakiet: 'Пакет',
        pakietDescription: 'Введіть назву або поштовий індекс міста, де ви хочете вибрати адресу для компанії. Доступні адреси та щомісячна вартість відображатимуться нижче.',
        updated: 'zaktualizowany',
        ended: 'kończy się',
        changePackage: 'zmień pakiet',
        packDescription1: 'Професійна адреса з повідомленнями  на пошту та телефон, а також відсутність доступу до нашої глобальної мережі ділових залів',
        packDescription2: 'Професійна адреса з повідомленнями  на пошту та телефон, а також відсутність доступу до нашої глобальної мережі ділових залів',
        packDescription3: 'Професійна адреса з повідомленнями  на пошту та телефон, а також відсутність доступу до нашої глобальної мережі ділових залів',
        packDescription4: 'Професійна адреса з повідомленнями  на пошту та телефон, а також відсутність доступу до нашої глобальної мережі ділових залів',
        rozliczenia: 'Розрахунки',
        rezerwacja: 'Бронювання офісу',
        myReservations: "Мої резервації",
        login: 'Логін',
        nameSurname: "Ім'я та прізвище",
        adress: 'Адреса',
        phone: 'Телефон',
        firmName: 'Назва компанії',
        nip: 'NIP',
        nipPlaceholder: 'NIP (податковий ідентифікаційний номер)',
        changePassword: 'Змінити пароль:',
        newPassword: 'Nowe Hasło',
        repeatPassword: 'Powtórz nowe hasło',
        passwordMessage1: "Hasło musi mieć co najmniej sześć znaków.",
        passwordMessage2: 'Hasło zostało pomyślnie zmienione!',
        passwordMessage3: "Powtórzone hasło nie jest zgodne z hasłem.",
        requiredField: 'Pole wymagane',
        all: 'УСІ',
        currentMonth: 'Obecny miesiąc',
        number: 'Номер',
        nazwa: 'Назва',
        date: 'Дата',
        wartosc: 'Сума',
        receipt: 'Квітанція',
        yourReservations: 'Ваші бронювання',
        code: 'kod dostępu:',
        yourDisplay: 'Ваш екран',
        displayText: 'Або введіть потрібний вам  текст.',
        yourPhrase: "Twoja fraza",
        menuContentText1: 'Дійте з будь-якої точки світу завдяки можливості віртуального офісу.',
        menuContentText2: "Зв'яжіться з нами:",
        authMessage1: 'Błąd zakupu pakietu.',
        authMessage2: 'Masz niedokończony pakiet.',
        authMessage3: 'there is no user or password wrong',
        authMessage4: 'This is an error message',
        authMessage5: 'Nie wygląda jak prawdziwy email adress...',
        authMessage6: 'Link do zresetowania hasła został wysłany na e-mail',
        authMessage7: 'This username is already in use by another account.',
        authMessage8: 'Password should be at least 6 digits',
        authMessage9: 'Passwords are not the same...',
        authMessage10: 'Nie wygląda jak prawdziwy numer telefonu.',
        authMessage11: 'The email address is already in use by another account.',
        authMessage12: 'E-mail podany podczas rejestracji',
        password: 'Password',
        email: 'E-mail',
        step: 'крок'

    },
    en: {
        footerOne: "Operate from any place around the world thanks to the virtual office option.",
        footerTwo: "Contact us:",
        cennikTitleOne: 'Virtual address',
        cennikTitleTwo: 'Optimum package',
        cennikTitleThree: 'Professional office',
        plnPerMonth: 'PLN / month',
        selectPackage: '1. wybór usługi biura wirtualnego:',
        selectPeriod: '2. wybierz profesjonalny adres swojej firmy:',
        month: 'Month',
        kwartal: 'Kwartał',
        year: 'Year',
        sum: 'summary',
        price: 'Price:',
        myProfile: 'Mój profil',
        pakiet: 'Pakiet',
        pakietDescription: 'Wpisz nazwę lub kod pocztowy miasta, w którym chcesz wybrać adres firmy. Dostępne adresy i miesięczny koszt wyświetlą się poniżej.',
        updated: 'zaktualizowany',
        ended: 'kończy się',
        changePackage: 'update',
        packDescription1: 'Profesjonalny adres z obsługą poczty i odbieraniem połączeń telefonicznych oraz dostęp bez rezerwacji do naszej globalnej sieci salonów biznesowych',
        packDescription2: 'Profesjonalny adres z obsługą poczty i odbieraniem połączeń telefonicznych oraz dostęp bez rezerwacji do naszej globalnej sieci salonów biznesowych',
        packDescription3: 'Profesjonalny adres z obsługą poczty i odbieraniem połączeń telefonicznych oraz dostęp bez rezerwacji do naszej globalnej sieci salonów biznesowych',
        packDescription4: 'Profesjonalny adres z obsługą poczty i odbieraniem połączeń telefonicznych oraz dostęp bez rezerwacji do naszej globalnej sieci salonów biznesowych',
        rozliczenia: 'Rozliczenia',
        rezerwacja: 'Rezerwacja biura',
        myReservations: "Moje Rezerwacje",
        login: 'Login',
        nameSurname: 'Imię i Nazwisko',
        adress: 'Adres',
        phone: 'Телефон',
        firmName: 'Nazwa Firmy',
        nip: 'NIP',
        nipPlaceholder: 'NIP',
        changePassword: 'Zmień hasło:',
        newPassword: 'Nowe Hasło',
        repeatPassword: 'Powtórz nowe hasło',
        passwordMessage1: "Hasło musi mieć co najmniej sześć znaków.",
        passwordMessage2: 'Hasło zostało pomyślnie zmienione!',
        passwordMessage3: "Powtórzone hasło nie jest zgodne z hasłem.",
        requiredField: 'Pole wymagane',
        all: 'Wszystkie',
        currentMonth: 'Obecny miesiąc',
        number: 'Nr',
        nazwa: 'Nazwa',
        date: 'Data',
        wartosc: 'Wartość',
        receipt: 'Paragon',
        yourReservations: 'Twoje rezerwacje',
        code: 'kod dostępu:',
        yourDisplay: 'Twój ekran',
        displayText: 'Lub wprowadź żądany tekst.',
        yourPhrase: "Twoja fraza",
        menuContentText1: 'Działaj z dowolnego miejsca na świecie dzięki opcji biura wirtualnego.',
        menuContentText2: 'Skontaktuj sie z nami:',
        authMessage1: 'Błąd zakupu pakietu.',
        authMessage2: 'Masz niedokończony pakiet.',
        authMessage3: 'there is no user or password wrong',
        authMessage4: 'This is an error message',
        authMessage5: 'Nie wygląda jak prawdziwy email adress...',
        authMessage6: 'Link do zresetowania hasła został wysłany na e-mail',
        authMessage7: 'This username is already in use by another account.',
        authMessage8: 'Password should be at least 6 digits',
        authMessage9: 'Passwords are not the same...',
        authMessage10: 'Nie wygląda jak prawdziwy numer telefonu.',
        authMessage11: 'The email address is already in use by another account.',
        authMessage12: 'E-mail podany podczas rejestracji',
        password: 'Hasło',
        email: 'E-mail',
        step: 'step'

    }
}

export const AuthTopLogin = ({language})=>(
    <>
        {language==='pl' && <>Zaloguj&nbsp;się</>}
        {language==='ua' && <>Увійти</>}
        {language==='en' && <>Log&nbsp;in</>}
    </>
)

export const AuthTopSignup = ({language})=>(
    <>
        {language==='pl' && <>Zarejestruj&nbsp;się</>}
        {language==='ua' && <>Зареєструватись</>}
        {language==='en' && <>Sign&nbsp;up</>}
    </>
)

export const AuthTopRecovery = ({language})=>(
    <>
        {language==='pl' && <>Odzyskiwanie&nbsp;hasła</>}
        {language==='ua' && <>Odzyskiwanie&nbsp;hasła</>}
        {language==='en' && <>Odzyskiwanie&nbsp;hasła</>}
    </>
)